version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "short-url-service"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1wplskjseb7hh"
s3_prefix = "short-url-service"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
